#!/usr/bin/env php
<?php

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

require_once __DIR__ . '/../vendor/autoload.php';

$config = include __DIR__ . './../config.php';

define('BASE_PATH', dirname(__DIR__));
define('LOG_PATH', BASE_PATH . '/logs');

use Symfony\Component\Console\Application;
use Go1\Command\SpreadsheetsCommand;
use Go1\Command\SpreadsheetsWriterCommand;
use Go1\Command\BrowsershotCommand;
use Go1\Command\SnappyCommand;

$app = new Application('Hackathon', '1.0.0');

$app->add(new SpreadsheetsCommand);
$app->add(new SpreadsheetsWriterCommand());
$app->add(new BrowsershotCommand());
$app->add(new SnappyCommand());
$app->run();
