#!/usr/bin/env php
<?php

    // if you don't want to setup permissions the proper way, just uncomment the following PHP line
    // read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
    //umask(0000);

    require_once __DIR__ . '/../vendor/autoload.php';

    define('APPLICATION_NAME', 'GO1 - Google Sheets API PHP');
    define('CREDENTIALS_PATH', '~/.credentials/sheets.googleapis.com-php_go1-spreadsheets.json');
    define('CLIENT_SECRET_PATH', __DIR__ . '/../client_secret.json');
    // If modifying these scopes, delete your previously saved credentials
    // at ~/.credentials/sheets.googleapis.com-php_go1-spreadsheets.json
    define(
        'SCOPES',
        implode(
            ' ',
            array(
                Google_Service_Sheets::SPREADSHEETS
            )
        )
    );

    define('BASE_PATH', dirname(__DIR__));
    define('LOG_PATH', BASE_PATH . '/logs');

    use Symfony\Component\Console\Application;
    use Go1\Command\SpreadsheetsCommand;

    $app = new Application();
    $app->add(new SpreadsheetsCommand);
    $app->run();